### PR TITLE
Add DJI cameras to sensor_data.json

### PR DESCRIPTION
**Pull request by dakotabenjamin**
as per: 
http://www.dji.com/product/phantom-3-pro/info#specs
http://www.dji.com/product/inspire-1/info#specs

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
In OpenDroneMap ccd_Defs.json, I used a regex word search to try to find discrepancies between the files. Below you can see my results after double-checking and removing duplicates. The values have not been checked for accuracy; I noticed that there are many discrepancies (differences +/- 0.1) between the two files. 
```
{
	"Canon Canon EOS DIGITAL REBEL XT": 22.2,
	"Canon Canon EOS DIGITAL REBEL XTi": 22.2,
	"Canon Canon EOS Kiss Digital": 22.66,
	"Canon Canon IXY DIGITAL 600": 7.176,
	"DJI FC300S": 6.16,
	"DJI FC300X": 6.2,
	"DJI FC350": 6.17,
	"DJI PHANTOM VISION FC200": 6.17,
	"GoPro HD2 U": 5.8,
	"GoPro HERO4 Black": 6.17,
	"GoPro HERO4 Silver": 6.17,
	"Gopro HD3": 5.76,
	"KONICA MILOLTA  DYNAX 5D": 23.5,
	"Mantis i23": 45.0,
	"Mobius Action Cam": 2.1,
	"NIKON COOLPIX L3": 5.76,
	"NIKON E2500": 5.27,
	"NIKON E3100": 5.27,
	"NIKON E3200": 5.27,
	"NIKON E3700": 5.27,
	"NIKON E4200": 7.176,
	"NIKON E4300": 7.18,
	"NIKON E4500": 7.176,
	"NIKON E4600": 5.76,
	"NIKON E5000": 8.8,
	"NIKON E5200": 7.176,
	"NIKON E5400": 7.176,
	"NIKON E5600": 5.76,
	"NIKON E5700": 8.8,
	"NIKON E5900": 7.176,
	"NIKON E7600": 7.176,
	"NIKON E775": 5.27,
	"NIKON E7900": 7.176,
	"NIKON E8800": 8.8,
	"NIKON E990": 7.176,
	"NIKON E995": 7.176,
	"Nokia N80": 5.27,
	"Nokia N93": 4.536,
	"Nokia N95": 5.7,
	"OLYMPUS_IMAGING_CORP.   X450,D535Z,C370Z": 5.27,
	"PHANTOM VISION FC200": 6.17,
	"SAMSUNG TECHWIN Pro 815": 8.8,
	"SONY DSC-HX5V": 6.104,
	"SONY DSC-N12": 7.176,
	"SONY ILCE-5100": 23.5,
	"SONY ILCE-7S": 35.8,
	"SONY SLT-A77V": 23.5,
	"Vexcel UltraCam": 28.0
}
```

**Comment by paulinus** [comment]
So the values above are the ones present in OpenDroneMap ccd_Defs.json and missing in opensfm?

**Comment by dakotabenjamin** [comment]
Yes, but like I said they are not verified for accuracy. There were minor errors with the DJI sensors that I fixed in this PR, which led me to believe there may be other errors. We were not strict with checking accuracy when accepting PRs for updating the ODM ccd_defs.json file.

**Comment by dakotabenjamin** [comment]
@paulinus How should we go about updating these keys? I've been getting some questions from ODM users on this topic.

**Comment by paulinus** [comment]
I'm adding those sensors to the db now.  Errors of 0.1 should be ok. The focal length reads from the EXIF will typically have errors of that magnitude too, so the initial calibration estimate that we get from this is approximate anyway.

**Pull request merged**
