### PR TITLE
Fixed loading graphic for viewer

### PR DESCRIPTION
**Pull request by Caboosey**
Fixed loading graphic since currently http://jimpunk.net/Loading/wp-content/uploads/loading1.gif is not working and being pulled via HTTP instead of HTTPS. Uploaded a good archived copy of graphic via archive.org

### CODE REVIEW

**Comment by paulinus** [comment]
Cool, thanks!

Do you think it would be possible to put the changes on a single commit?

**Comment by Caboosey** [comment]
@paulinus Whoever has admin rights can do this. https://github.com/blog/2141-squash-your-commits

**Comment by EderSantana** [comment]
@paulinus you can now setup github to auto squash the commits https://github.com/blog/2141-squash-your-commits

**Comment by paulinus** [comment]
@Caboosey ok, i see why the trial and error commits. Thanks for spotting the problem. I went ahead and made the changes on master (https://github.com/mapillary/OpenSfM/commit/38e79e3e429a9666ee01b77b737250608bca1fe9). We were using a random gif from the net, which we might not have the right to include on the repo. So i've added a gif that we own. Thanks again.

@EderSantana thanks for the tip, didn't know github can squash commits.

**Pull request closed without merging**
