### PR TITLE
Enable building on Windows again

### PR DESCRIPTION
**Pull request by yilangmok**
- Add detailed instructions on how to build on Windows
- Fix incompatible `Pillow>=8.1.1` and `fpdf2==2.1.0` requirements by upgrading to `fpdf2-2.4.6`
- Add `#define _USE_MATH_DEFINES` before `#include <cmath>` to expose non-standard `M_PI` constants
- Remove unused `memory_usage()` from `log.py`, which allows removing the `resource` import which is not available on Windows
- Add `bin\opensfm_run_all.bat` to mirror `bin\opensfm_run_all`

Tested on Windows 11 in a fresh VM.

Combined fixes from https://github.com/mapillary/OpenSfM/pull/772 (`fpdf2`) and https://github.com/mapillary/OpenSfM/issues/828 (`M_PI`).

### CODE REVIEW

**Comment by yilangmok** [comment]
@fabianschenk could you share what the failures are? Thanks!

**Comment by fabianschenk** [comment]
HI @yilangmok ,

Thanks for the PR :D 
The method `memory_usage` is not used inside OpenSfM but required somewhere else but of course you couldn't have known that.
I'll try to refactor our internal code a bit but I've a ton ofter things to do, so this might take a bit.

Thanks again,
Fabian

**Comment by yilangmok** [comment]
Haha secret code!

I notice that these functions are duplicated in https://github.com/mapillary/OpenSfM/blob/13b0b659204a0e2e7041c79b680813ca20073891/opensfm/context.py#L64, which correctly handles the Windows use case. I wonder if we can just rewrite `log.py` to call `context.py`?

**Comment by fabianschenk** [comment]
Hey @yilangmok ,

I already implemented a fix and your tests now pass internally. Just waiting for the review :D

**Comment by yilangmok** [comment]
@fabianschenk thanks so much for merging this!

**Pull request closed without merging**
