### PR TITLE
Add third parameter for radial distortion for perspective camera

### PR DESCRIPTION
**Pull request by lamerman**
Currently only K1 and K2 are used by the algorithm, while K3
is needed for certain cameras.

### CODE REVIEW

**Comment by lamerman** [comment]
So the idea here is that we introduce a concept of distortion model which currently can be:
- radial k1+k2
- radial k1+k2+k3
In the future I assume it should at least include tangential distortions (not the scope of this change).

Every perspective camera has a configurable distortion model. Fisheye as I understand also should have one, it's not yet implemented.

**Comment by lamerman** [comment]
The difference in bundle adjustment score for galaxy s7 camera calibrated on checkerboard with 2 and 3 parameters is:
Final cost:  4.468651e+02 for 2 parameters
Final cost:  3.657365e+02 for 3 parameters

The scene contains 22 outdoor images.

I previously said the difference was order of magnitude in the issue #165, so it was not true, that measurements were not correct :)  The difference is less, but still present and seem to be stable.

**Comment by paulinus** [comment]
That is great, @lamerman !

While we can indeed add the concept of "distortion model" we can also consider each distortion model as a new `projection_type`. We currently have `perspective`, `fisheye` and `equirectangular` projection models. We can add a 4th one that could be named `brown` and that would have the 5 distortion parameters of the Brown-Conrady distortion model.

That has the advantage that we can keep the current `perspective` model unchanged and we can freely play with the new `brown` model without breaking anything. The disadvantage is that we need to duplicate some code but i think it would be cleaner like this. What do you think?

**Comment by lamerman** [comment]
@paulinus I think you are right, maybe it would be better to implement the full model (radial+tangential distortions) at once in a separate class. 

Right now I have some problems with time, but if I have some time window (hopefully) in the nearby future I will implement it. Please keep track in the task if someone has started to make it.

I'll close the PR now, as this code can't be reused for that implementation.

**Comment by bdholt1** [comment]
Hi @lamerman and @paulinus - this is something that I'd like as well.  I'm happy to start on the implementation and help out. Perhaps we can work together on it?

**Comment by lamerman** [comment]
@bdholt1 I'm not working on it now :) feel free to start.

**Comment by bdholt1** [comment]
> While we can indeed add the concept of "distortion model" we can also consider each distortion model as a new projection_type. We currently have perspective, fisheye and equirectangular projection models. We can add a 4th one that could be named brown and that would have the 5 distortion parameters of the Brown-Conrady distortion model.

>That has the advantage that we can keep the current perspective model unchanged and we can freely play with the new brown model without breaking anything. The disadvantage is that we need to duplicate some code but i think it would be cleaner like this. What do you think?

If I understand @paulinus correctly, the proposal is to create a new class (in types.py)

`class BrownConradyPerspectiveCamera(Camera):`

which will have k3, p1 and p2 parameters; and a corresponding new projection_type 'brown'.

This will certainly result in some duplicated code (basically copy/paste PerspectiveCamera and add the new distortion coefficents) and it is 'cleaner' in the sense that if won't break existing code. The main drawback here is that any benefit gained by adding the new distortion coefficients will not be enjoyed by the Fisheye camera model (we'd need to create a new BrownConradyFisheyeCamera and projection type).

This PR started down the road of attempting to avoid that by introducing a 'distortion model' in the PerspectiveCamera but it's implementation only considered the PerspectiveCamera, so once again the benefits could not be enjoyed by the Fisheye camera.

An alternative would be to try to decouple the Camera and the Distortion model such that Camera 'has a ' distortion.  Intuitively this makes sense - they are independent concepts.

To decouple the concepts would look a bit like this current PR, but would introduce a new class in types.py called Distortion.We could then support different distortion models, for example (K1,K2) as is currently done as well as any number of new distortion models (K1,K2,P1,P2,K3) etc and then both Perspective and Fisheye cameras can have a Distortion.  The biggest changes will be in the bundle adjustment code.

Is it worth pursuing this idea?  The downside is that it's likely to impact existing code quite signficantly.

**Comment by paulinus** [comment]
The ideal case would be that the current PerspectiveCamera already included those parameters and a way to choose which ones to optimize. We may end up there but I think it is easier to do it by adding a new camera model. If that camera model eventually gets flexible enough, it might replace the current perspective one. But I think it is a good idea to keep the current one untouched not to break existing reconstructions.

On separating the distortion model from the camera model, I don't think it is worth the effort. What is left on a camera model if you remove the distortion model?  A distortion model **is** a camera model.

Note for example that you can not build a distortion model that would work for both perspective and fisheye camera models.  While the models share the parameter names and a polynomial expression, the polynomial is applied to different radius concepts.

`<philosophy>`
We call it distortion because we think of it as a deviation from the ideal pinhole model. But there is another way to look at it that works for more camera models.

The goal of a (central) camera model is to map 3D points to 2D pixels and 2D pixels to 3D bearings.  These mappings may include a simple perspective projection or more involved, non-linear functions. As long as you can define the mapping, you have a camera. There is no need to define the mapping as a distortion from the pinhole model.
`</philosophy>`

So all in all, I would go for starting with a copy-paste of the current PerspectiveCamera and add the parameters there.

**Pull request closed without merging**
