### PR TITLE
feat: statistics and report

### PR DESCRIPTION
**Pull request by YanNoun**
This PRs aims at adding two commands (`compute_statistics`) and (`export_report`), that allows computing various quality metrics of a dataset and export them as a nice PDF report :

 - `compute_statistics` will generate various image files (mostly plots) and a stats.jsopn file in the `stats` folder.
 - `export_report` will use the above to generate some PDF.

cc @pierotofy as it might be of interest for you.

See below for an example of the Red Rocks dataset (https://dronemapper.com/sample_data/) :
[report.pdf](https://github.com/mapillary/OpenSfM/files/5510820/report.pdf)

### CODE REVIEW

**Comment by pierotofy** [comment]
This is amazing :heart: 

What a wonderful addition!

**Comment by smathermather** [comment]
Yeah, this is one of the most commonly requested features in OpenDroneMap. Folx are going to be ecstatic.

**Comment by YanNoun** [comment]
@pierotofy it's finally merged !

**Comment by pierotofy** [comment]
Can't wait to try this! 

Thanks for this awesome addition @YanNoun

**Pull request closed without merging**
