### PR TITLE
python3 and boost 1.65 changes

### PR DESCRIPTION
**Pull request by spease**
This still doesn't work, but is some amount along. I'm just about done for the night and probably won't have any more time to work on this.

Note that this also tries to fix the Boost python numeric deprecation errors as well, with a slightly different (maybe more generic?) approach than I saw in opengv.

This isn't my usual cup of tea, so be extra skeptical.
```
2017-12-22 02:22:55,247 INFO: Extracting focal lengths for image 01.jpg
2017-12-22 02:22:55,290 INFO: Extracting focal lengths for image 03.jpg
2017-12-22 02:22:55,326 INFO: Extracting focal lengths for image 02.jpg
2017-12-22 02:22:56,513 INFO: Extracting ROOT_HAHOG features for image 02.jpg
2017-12-22 02:22:56,514 INFO: Extracting ROOT_HAHOG features for image 01.jpg
2017-12-22 02:22:56,559 INFO: Extracting ROOT_HAHOG features for image 03.jpg
2017-12-22 02:22:56,678 INFO: Found mask to apply for image 01.jpg
2017-12-22 02:22:56,680 INFO: Found mask to apply for image 02.jpg
2017-12-22 02:22:56,721 INFO: Found mask to apply for image 03.jpg
Traceback (most recent call last):
  File "/home/spease/projects/carlos/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/spease/projects/carlos/OpenSfM/opensfm/commands/detect_features.py", line 30, in run
    parallel_map(detect, arguments, processes)
  File "/home/spease/projects/carlos/OpenSfM/opensfm/context.py", line 38, in parallel_map
    return list(e.map(func, args))
  File "/home/spease/projects/carlos/OpenSfM/env/lib/python3.6/site-packages/loky/process_executor.py", line 769, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/spease/projects/carlos/OpenSfM/env/lib/python3.6/site-packages/loky/_base.py", line 584, in result_iterator
    yield future.result()
  File "/home/spease/projects/carlos/OpenSfM/env/lib/python3.6/site-packages/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/home/spease/projects/carlos/OpenSfM/env/lib/python3.6/site-packages/loky/_base.py", line 382, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

### CODE REVIEW

**Comment by paulinus** [comment]
That's great, @spease. Thanks for getting this started. It will take some time for us to be able to merge this to master but we are really looking forward to starting python3 support.

Quick question: are the changes in this PR intended to make it work with python3 only or on both 2 and 3?

**Comment by paulinus** [comment]
For boost 1.65 and opengv, I've started playing with it here https://github.com/laurentkneip/opengv/compare/master...paulinus:boost-python-numpy
Will compare that to the approach you took here.

**Comment by spease** [comment]
Only python3 - I primarily ran the 2to3 tool on python scripts and then manually fixed some errors relating to the Json encoding. Nb that by fixed I mainly mean removing it, so far everything had used utf-8 encoding and it didn't look like there was an easy way to specify since the Json library writes strings and the encoding argument looked like it was being passed after files were being opened (best option would probably be to set the file encoding).

Build.py is probably compatible with both from me including the future import.

Note that the cmakelists probably needs more work to work with different platforms and versions, since some platforms use boost-python_py36 instead of just boost python3 from reading about other conversation efforts out there. I saw tickets both for a fallback in that case, and a cmake ticket to make things pick the correct variant based on just a single specifier.

**Comment by paulinus** [comment]
We have added initial python 3 support maintaining python 2 compatibility. Thanks for paving the way @spease !

**Pull request closed without merging**
