### PR TITLE
Add time zone support to time stamp extraction

### PR DESCRIPTION
**Pull request by GITNE**
`DateTime*` time stamps are adjusted by time zone offsets `OffsetTimeOriginal`, `OffsetTimeDigitized`, and `OffsetTime` respectively, if available. Otherwise, UTC is naively assumed on any `DateTime*`.

The time stamp is extracted in the following order of decreasing precedence:
 * `GPSDateStamp` and `GPSTimeStamp`
 * `DateTimeOriginal` + `SubSecTimeOriginal` + `OffsetTimeOriginal`
 * `DateTimeDigitized` + `SubSecTimeDigitized` + `OffsetTimeDigitized`
 * `DateTime` + `SubSecTime` + `OffsetTime`
 * `DateTimeOriginal` + `SubSecTimeOriginal` (*UTC*)
 * `DateTimeDigitized` + `SubSecTimeDigitized` (*UTC*)
 * `DateTime` + `SubSecTime` (*UTC*)

### CODE REVIEW

**Comment by GITNE** [comment]
@paulinus This PR is probably not absolutely required for OpenSfM to work, since OpenSfM only depends on proper relative ordering of images, not absolute ordering. Anyhow, correct absolute time stamp extraction may be useful for some users, including Mapillary, although I am not sure at which stage of the Mapillary backend a time stamp is extracted. It would be nice to finally have this *feature* on the website. :wink:

**Comment by GITNE** [comment]
> I am not sure at which stage of the Mapillary backend pipeline a time stamp is extracted.

@peterneubauer Perhaps you can comment on this. Currently, I am still very upset that time zone support does not work as expected…

**Comment by peterneubauer** [comment]
Our precendence in the Mapillary backend currently is this:

```
"EXIF DateTimeOriginal",
"Image DateTimeOriginal",
"EXIF DateTimeDigitized",
"Image DateTimeDigitized"
"GPSTime"
"Image DateTime",
"EXIF DateTime"
```

@paulinus do you think it makes sense to change to the same order as suggested here?

**Comment by GITNE** [comment]
> Our precendence in the Mapillary backend currently is this:
> ```
> "Image DateTimeOriginal",
> "Image DateTimeDigitized",
> "Image DateTime"
> ```
@peterneubauer I am not sure what you mean by *`Image`*?

The reason why I would go with `GPSTimeStamp` first is because it is the only time zone aware time stamp ever since EXIF 1.0. So, this should always work, even though not all devices write this tag. Then, we basically agree on the general order of precedence of `DateTime*` tags. However, time zone offsets denoted by `OffsetTime*` (if available) should be applied on `DateTime*` tags before finally falling back to and naively assuming UTC.
Changing the precedence on the backend and updating the database on all images *should* *not* be very expensive, since this is an extremely cheap operation, even though it may take some time.

**Pull request merged**
