### PR TITLE
Plot inliers

### PR DESCRIPTION
**Pull request by oscarlorentzon**
To visualize the results for some of the algorithms that includes or excludes feature matches along the pipeline I have created some functions that plot inliers and outliers. 

Two images from a data set needs to specified when running the file but since functions have been extracted a loop can easily be created to plot a number of image combinations.

Because the algorithms are actually run using loaded features and tracks the figures are not created instantly.

The results for two images in the Berlin data set can be seen below:

##### Features and symmetric matches as well as inliers and outliers of robust matches for image 01 and 03:

01 jpg_03 jpg_sift_matches

##### Common tracks (corresponding and not corresponding to robust matches) as well as inliers and outliers of OpenCV find homography and CSfM two view reconstruction:

01 jpg_03 jpg_sift_tracks

### CODE REVIEW

**Comment by jesolem** [comment]
This is awesome @oscarlorentzon !!

**Comment by oscarlorentzon** [comment]
Thanks!

**Comment by ybkuang** [comment]
Great work @oscarlorentzon. This is very useful for visualizing/debugging!

**Comment by oscarlorentzon** [comment]
Thanks again!

**Comment by niranjantdesai** [comment]
Can we include this in the documentation? I almost missed this and was going to write my own visualization functions.

**Pull request merged**
