### PR TITLE
Allow per image masking

### PR DESCRIPTION
**Pull request by BrookRoberts**
Adding additional feature where you can mask out parts of the image on a frame by frame and pixel by pixel basis, rather than having to specify static rectangles for the whole range.

Masks should have the same name as the corresponding image, and are listed in the same way as images, i.e. you can provide a textfile listing them, or you can just dump them in a folder next to images, called 'masks'.  They should be image files of the same dimension as the original images.  The first channel is scanned, and if it is equal to 0 then features there are kept, and if it is non-zero they aren't. (i.e. for a black and white mask, any white areas of the mask are deemed not useful, e.g. watermarks, moving objects, and so on).

Is there any relevant documentation to update?  I've also not really looked into the tests associated with OpenSFM, so would appreciate some pointers there if appropriate.  I did also for my own testing make something that would output images of the location of features found, before and after mask filtering.  I don't think these should be included, but am happy to put them somewhere if useful.  Was certainly useful for being really sure what was going on.

#118

### CODE REVIEW

**Comment by paulinus** [comment]
This is really great @BrookRoberts ! Thanks for adding that.

I only have minor comments on it
- We try to avoid opening files from disk outside the `Dataset` class. This is because, we have alternative versions of the `Dataset` class that load files from the network. So instead of loading the masks in `features.py`, it would be better to have a method like `Dataset.mask_as_array(image)` in `dataset.py` 
- Really minor: I don't think there is any standard, but i'm used to consider 0 as the mask out value. White is keep and black is ignore. Would it be ok for you to reverse?

**Comment by BrookRoberts** [comment]
Thanks!

First comment sounds reasonable, I'll change that.
Second comment - yes, I guess that makes slightly more sense.  It wasn't entirely obvious to me which way made more sense and my way fit better with my current outputs!

I'll try and fix this up soonish.

**Comment by paulinus** [comment]
awesome, thanks!

**Comment by BrookRoberts** [comment]
Right, have made a commit that hopefully addresses those issue.

**Comment by paulinus** [comment]
Good fixes @BrookRoberts!  I had a problem when testing with images larger than 2048 since the width and height of the image is then smaller than the size of the mask. I have a fix working. I'll merge this PR and commit the fix after that.

**Comment by paulinus** [comment]
I'm also going to change the name of the mask files so that the mask of `images/im1.jpg` is `images/im1.jpg.png`. It is a bit ugly to add a second extension to a file name, but it makes it very easy to map the image name to the mask file.

This makes it easy to have masks in PNG format regardless of the format of the original images. Otherwise, JPG images need to have JPG masks, which is not a good format for binary images.

I hope that works for you. Thanks for the PR!

**Pull request merged**
